/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author
 * Kevin
 */
public class puMenu extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 8912915752772778219L;
	/**
     * Creates
     * new
     * form
     * puMenu
     */
    public puMenu() {
        initComponents();
    }

    /**

					THIS ENTIRE CLASS WAS GENERATED BY NETBEANS from the GUI builder
					THIS ENTIRE CLASS WAS GENERATED BY NETBEANS from the GUI builder
					THIS ENTIRE CLASS WAS GENERATED BY NETBEANS from the GUI builder
					THIS ENTIRE CLASS WAS GENERATED BY NETBEANS from the GUI builder
					THIS ENTIRE CLASS WAS GENERATED BY NETBEANS from the GUI builder
					THIS ENTIRE CLASS WAS GENERATED BY NETBEANS from the GUI builder
					THIS ENTIRE CLASS WAS GENERATED BY NETBEANS from the GUI builder
					THIS ENTIRE CLASS WAS GENERATED BY NETBEANS from the GUI builder
					THIS ENTIRE CLASS WAS GENERATED BY NETBEANS from the GUI builder
					THIS ENTIRE CLASS WAS GENERATED BY NETBEANS from the GUI builder
					THIS ENTIRE CLASS WAS GENERATED BY NETBEANS from the GUI builder
					THIS ENTIRE CLASS WAS GENERATED BY NETBEANS from the GUI builder
					THIS ENTIRE CLASS WAS GENERATED BY NETBEANS from the GUI builder
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        dragonimage = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dragon Oath V PlayOnline Launcher/Patcher");

        dragonimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dragon oath v.png"))); // NOI18N

        playButton.setText("Play Dragon Oath V: The Next Generation -  Pu Liu's Journey");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(playButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dragonimage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dragonimage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playButton, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           

		Thread gthread = new Thread(new GThread());
		gthread.start();
    }                                          

    /**
     * @param
     * args
     * the
     * command
     * line
     * arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(puMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(puMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(puMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(puMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new puMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JLabel dragonimage;
    private javax.swing.JButton playButton;
    // End of variables declaration                   
}
